.\"-
.\" BSD 2-Clause License
.\"
.\" Copyright (c) 2025, Muhammad Saheed <saheed@FreeBSD.org>
.\"
.Dd April 3, 2025
.Dt WUTIL 1
.Os
.Sh NAME
.Nm wutil
.Nd "A WiFi utility"
.Sh SYNOPSIS
.Nm
.Ar command ...
.Sh DESCRIPTION
.Nm
is a CLI for managing and configuring network interfaces.
It provides commands for listing interfaces, enabling or disabling them,
configuring network settings,
scanning for available wireless networks, and connecting to them.
.Sh EXIT STATUS
.Ex -std
.Sh COMMANDS
These commands can be supplied on the command line.
.Bl -tag -width indent
.It Ic list
List all available network interfaces and their status.
.It Ic show Ar interface
Display status of the
.Ar interface .
.It Ic enable Ar interface
Enable the
.Ar interface .
.It Ic disable Ar interface
Disable the
.Ar interface .
.It Ic restart Ar interface
Restart the
.Ar interface .
.It Xo
.Ic configure Ar interface Bo
.Op Fl --method Ar dhcp | manual
.Op Fl --ip Ar address
.Op Fl --netmask Ar netmask
.Bc
.Op Fl --gateway Ar gateway
.Op Fl --dns1 Ar dns_server
.Op Fl --dns2 Ar dns_server
.Op Fl --search Ar domain
.Xc
Configure
.Op ip ,
.Op netmask ,
.Op gateway ,
dns resolvers and
.Op search
domain for the
.Ar interface .
.It Ic scan Ar interface
Scan for available wireless networks on the
.Ar interface .
.It Ic connect Ar interface Ar ssid Op Ar psk
Connect to the wireless network with the
.Ar ssid
and optionally with the password
.Ar psk
.It Ic disconnect Ar interface
Disconnect from the current wireless network on the
.Ar interface .
.It Ic help
Display usage information.
.El
.Sh EXAMPLES
Scan for wireless networks on
.Pa wlan0 :
.Pp
.Dl # wutil scan wlan0
.Pp
Connect to the network
.Pa FreeButBased
with password
.Pa 1234 :
.Pp
.Dl # wutil connect FreeButBased 1234
.Pp
Enable the interface
.Pa wlan0 :
.Pp
.Dl # wutil enable wlan0
.Pp
Set the DNS resolver to
.Pa 1.1.1.1
and
.Pa 1.0.0.1
.Pp
.Dl # wutil configure wlan0 --dns1 1.1.1.1 --dns2 1.0.0.1
.Sh SEE ALSO
.Xr ifconfig 8
.Sh AUTHORS
.An Muhammad Saheed Aq Mt muhammad.saheed.iam@gmail.com
